#ifndef SRC_DEFS_H_
#define SRC_DEFS_H_


#define WINDOW_SIZE_HORIZONTAL 800
#define WINDOW_SIZE_VERTICAL 600


#define JUGADOR_SIZE_HORIZONTAL 150
#define JUGADOR_SIZE_VERTICAL 250

#define JUGADOR_POSICION_HORIZONTAL_INICIAL 100
#define JUGADOR_POSICION_VERTICAL_INICIAL 600-250-50

//Para el source
#define ANCHO_CAPA_PIXELES 2250
//Para el destino
#define ANCHO_CAPA_PIXELES_ESCALADA 2250 *2.05

#define MARGEN_IZQUIERDO 50
#define MARGEN_DERECHO 200

#define VELOCIDAD_CODY 6
#define VELOCIDAD_SALTO_INICIAL 30
#define ALTURA_MAXIMA 200 //Lo maximo que puede saltar cody
#define GRAVEDAD -5
#define DELTA_T 0.16


#endif /* SRC_DEFS_H_ */
